development:
  adapter: postgresql
  host: localhost
  database: my_database_development
  pool: 5
  timeout: 5000

#test  
test:
  adapter: postgresql
  host: localhost
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: my_database_production
  pool: 5
  timeout: 5000
